### ISSUE TITLE
 Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by Mahamod-Sahil** [bishalcpgn/LAMP_Automated#1]
OS used : Parrot OS 5.3 (Electro Ara)

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock'
stty: 'standard input': Inappropriate ioctl for device
Enter current password for root (enter for none): 
stty: 'standard input': Inappropriate ioctl for device

**Comment by bishalcpgn** [comment]
fixed
